name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tomersf/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tomersf/react-test npm test -- --watchAll=false
 
      - run: docker build -t tomersf/multi-client ./client
      - run: docker build -t tomersf/multi-nginx ./nginx
      - run: docker build -t tomersf/multi-server ./server
      - run: docker build -t tomersf/multi-worker ./worker
 
      - run: docker push tomersf/multi-client
      - run: docker push tomersf/multi-nginx
      - run: docker push tomersf/multi-server
      - run: docker push tomersf/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-995673743848
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip